### PR TITLE
remove_s4_classes() respecting inheritance

### LINKED ISSUE #848: load_all() error when using setOldClass() with inheritance
I have prepared a [MRE](https://github.com/famuvie/testpkg) for this issue, as a dummy package that can be installed and tested quickly.

In summary, I need to register some S3 classes with inheritance structure using `setOldClass()`.
```R
#' @importFrom methods setOldClass
methods::setOldClass(c('derived_class', 'my_class'))
```
When I `load_all()` for the first time, everything goes fine. But for successive times, it fails as follows:
```
Loading testpkg
Error in methods::setOldClass(c("derived_class", "my_class")) (from testmethod.R#3) : 
  inconsistent old-style class information for “derived_class”; the class is defined but does not extend “my_class” and is not valid as the data part
```

**Variations:**
- The error **does not** occur if the class to be registered is single (i.e. `setOldClass('my_class')`).
- Incomprehensibly, it **does not occur** either  if the derived class name is `'splines'` (!?!?)
- Finally, the error **still occurs** if I register `'my_class'` beforehand in a separate sentence.

```
> session_info()
Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        

Packages -------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 devtools     1.7.0   2015-01-17 CRAN (R 3.1.2)
 digest     * 0.6.8   2014-12-31 CRAN (R 3.2.0)
 memoise    * 0.2.1   2014-04-22 CRAN (R 3.1.2)
 Rcpp       * 0.11.5  2015-03-06 CRAN (R 3.1.3)
 roxygen2   * 4.1.1   2015-04-15 CRAN (R 3.2.0)
 rstudioapi * 0.3.1   2015-04-07 CRAN (R 3.2.0)
 stringr    * 0.6.2   2012-12-06 CRAN (R 3.1.2)
```

### PR DESCRIPTION
**Pull request by famuvie**
prevents derived classes to remain orphan
Fixes #848

### CODE REVIEW

**Comment by famuvie** [comment]
Mmm... contrary to #848, with this reverse removing of classes the error arises when the derived class is named 'splines'. What is it special with this name?

**Comment by famuvie** [comment]
Ok. There is nothing particular with the class name `splines` except for the fact that alphabetically comes after `my_class`. The current `devtools` version removes classes by alphabetical order which happen to coincide with inheritance hierarchy (i.e. `my_class` is extended by `splines`).

I needed to write a small routine to sort the classes defined in the package, so that extended classes are before their respective extensions. With this approach I think the problem is solved.

**Comment by hadley** [comment]
@wch happen to remember an elegant way to do this?

**Comment by hadley** [comment]
Ideally you'd do a topological sort on the S4 dependency graph before deleting

**Comment by famuvie** [comment]
Right. My solution worked for me, but not necessarily in general.
Implemented a topological sorting. Not very fast in R, but graphs of classes should not be huge.

**Comment by hadley** [comment]
Could you please add some unit tests for `sort_s4classes()`?

**Comment by famuvie** [comment]
sure... in a couple of weeks.

**Comment by famuvie** [comment]
Done, with some modifications thanks to the testing.
Incidentally, this fixes one previously failing check that was commented out in `test-s4-unload.R`.

File: R/remove-s4-class.r [hunk 1]
```diff
@@ -6,7 +6,60 @@ remove_s4_classes <- function(pkg = ".") {
...
+
+  ## Return the parent class, if any within domestic classes
+  extends_first <- function(x, classes) {
+    ext <- extends(getClass(x, where = nsenv))
+    parent <- ext[2]
+    classes %in% parent
+  }
+
+  ## Matrix of classes in columns, extending classes in rows
+  extended_classes <- vapply(classes,
```
Comment (hadley) [inline R/remove-s4-class.r]: Please indent arguments by only two spaces

File: tests/testthat/test-s4-unload.r [hunk 2]
```diff
@@ -46,7 +46,10 @@ test_that("loading and reloading s4 classes", {
   # Check that classes are unregistered
   # This test on A fails for some bizarre reason - bug in R? But it doesn't
```
Comment (hadley) [inline tests/testthat/test-s4-unload.r]: Can you please just delete this whole comment block? i.e. 47-51

**Comment by hadley** [comment]
Could you please also add a bullet to NEWS?

File: tests/testthat/testS4sort/DESCRIPTION [hunk 3]
```diff
@@ -0,0 +1,11 @@
+Package: testS4sort
+Title: Test package for sorting S4 classes
+License: GPL-3
```
Comment (wch) [inline tests/testthat/testS4sort/DESCRIPTION]: I think it would be best to just take out the `License` field here. Or it should be the same license as devtools itself.

**Comment by famuvie** [comment]
Done.

**Comment by hadley** [comment]
Thanks!
